open polar_sequence.txt

reliability_sequence = [polar_sequence(1:16:end); ...
    polar_sequence(3:16:end); ...
    polar_sequence(5:16:end); ...
    polar_sequence(7:16:end); ...
    polar_sequence(9:16:end); ...
    polar_sequence(11:16:end); ...
    polar_sequence(13:16:end); ...
    polar_sequence(15:16:end)];

polar_sequence_prime = [polar_sequence(2:16:end); ...
    polar_sequence(4:16:end); ...
    polar_sequence(6:16:end); ...
    polar_sequence(8:16:end); ...
    polar_sequence(10:16:end); ...
    polar_sequence(12:16:end); ...
    polar_sequence(14:16:end); ...
    polar_sequence(16:16:end)];

polar_sequence = polar_sequence_prime;

save reliability_sequence reliability_sequence
save polar_sequence polar_sequence